---

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install Ansible Galaxy dependencies
      local_action: command ansible-galaxy install geerlingguy.nfs --roles-path ./roles

- hosts: all
  become: yes
  tasks:
    - name: Ensure APT caches updated
      apt:
        update_cache: yes

- include: master.yml
- include: slaves.yml
- include: test_cluster.yml
